version: '2'

services:
  nginx:
      image: nginx:alpine
      volumes: 
          - ./client/dist:/usr/share/nginx/html
      links:
          - go:go
      ports:
          - "80:80"
  go:
      image: golang:1.6.1-alpine
      volumes: 
          - ./server:/go/src/github.com/patmigliaccio/go-web/server/
      working_dir: /go/src/github.com/patmigliaccio/go-web/server/
      command: go run main.go
      environment:
        PORT: '5000'
        REDIS_URL: 'redis://redis:6379'
      links:
          - redis
      ports:
          - "8080"
  redis:
      image: redis
      ports:
          - "6379"