# Environment Variables

[server]
host = "localhost"
port = 8080

[web]
location = "../client/dist"

[web.assets]
route = "/static"
location = "../client/dist/static"

[web.rest]
root = "/api/v0"

[redis]
SvcHost = "localhost"
SvcPort = 4040
SvcProtocol = "http" # https
DbHost = "192.168.99.100"
DbPort = 32168
DbPassword = ""
Db = 0
