[app]
title = "Go Web Application by Pat Migliaccio"
author = "Pat Migliaccio <pat@patmigliaccio.com> (https://patmigliaccio.com/)"

# Environment Variables

[server]
port = 8080

[web]
location = "../public"

[web.assets]
route = "/assets"
location = "../public/assets"

[web.rest]
root = "/api/v0"

[redis]
SvcPort = 4040
DbHost = "localhost"
DbPort = 6379
DbPassword = ""
Db = 0
