[app]
title = "Go Web Application by Pat Migliaccio"
author = "Pat Migliaccio <pat@patmigliaccio.com> (https://patmigliaccio.com/)"

# Environment Variables

[server]
port = 8080

[web.assets]
route = "/assets"
location = "../public/assets"

[web.api]
root = "/api/v0"
